export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2d3133", 
        "on-error-container": "#ffdad6", 
        "on-secondary-fixed": "#07006c", 
        "on-primary-fixed-variant": "#004c6e", 
        "on-surface": "#e0e3e5", 
        "on-tertiary-fixed-variant": "#653e00", 
        "on-error": "#690005", 
        secondary: "#c0c1ff", 
        "on-primary-container": "#003751", 
        "surface-container-highest": "#323537", 
        "on-tertiary-fixed": "#2a1700", 
        error: "#ffb4ab", 
        "surface-container-high": "#272a2c", 
        "error-container": "#93000a", 
        "inverse-surface": "#e0e3e5", 
        "surface-dim": "#101415", 
        "surface-container-lowest": "#0b0f10", 
        "on-primary-fixed": "#001e2f", 
        "on-background": "#e0e3e5", 
        "on-tertiary-container": "#4a2c00", 
        "primary-fixed-dim": "#89ceff", 
        "on-tertiary": "#472a00", 
        surface: "#101415", 
        "inverse-primary": "#006591", 
        "primary-fixed": "#c9e6ff", 
        "on-secondary-fixed-variant": "#2f2ebe", 
        "tertiary-fixed": "#ffddb8", 
        "secondary-fixed": "#e1e0ff", 
        "on-primary": "#00344d", 
        "surface-container-low": "#191c1e", 
        background: "#101415", 
        "surface-container": "#1d2022", 
        "surface-variant": "#323537", 
        "tertiary-fixed-dim": "#ffb95f", 
        "on-secondary-container": "#b0b2ff", 
        outline: "#88929b", 
        primary: "#0ea5e9", 
        "primary-container": "#e0f2fe", 
        "on-primary": "#ffffff",
        "on-primary-container": "#0369a1",
        secondary: "#64748b",
        "secondary-container": "#f1f5f9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0f172a",
        background: "#0f172a",
        surface: "#1e293b",
        "on-surface": "#f8fafc",
        outline: "#334155"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem", 
        lg: "2rem", 
        xl: "3rem", 
        full: "9999px"
      }
    },
  },
  plugins: [],
}
